events {
  worker_connections  1024;
}

http {
    server {
        listen 80;
        listen [::]:80;
        
        server_name localhost;

        root /usr/share/nginx/html;

        location ~ \.(gif|jpg|png)$ {
            root /data/images;
        }

        location /welcome {
            return 200 'bienvenido';
            add_header Content-Type text/plain;
        }

        location / {
          try_files $uri $uri/ =404;
        }
    }
}
