resources:
- ../../base

namePrefix: perfix-
nameSuffix: -suffix

namespace: dev

labels:
  - pairs:
      environment: dev
    includeSelectors: true
    includeTemplates: true

commonAnnotations:
  - pairs:
      environment: dev

images:
- name: nginx
  newTag: "1.27"

replicas:
- name: nginx-app
  count: 5
